import type { Question } from './propertyQuestions';

export const BUYER_QUESTIONS: Question[] = [
  {
    id: 'emotion',
    title: 'Émotion recherchée',
    subtitle: 'Je veux que mon bien coup de cœur soit…',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'apaisante', label: 'Apaisante', emoji: '🧘' },
      { value: 'inspirante', label: 'Inspirante', emoji: '💡' },
      { value: 'chaleureuse', label: 'Chaleureuse', emoji: '🔥' },
      { value: 'energisante', label: 'Énergisante', emoji: '⚡' },
      { value: 'securisante', label: 'Sécurisante', emoji: '🛡️' },
      { value: 'impressionnante', label: 'Impressionnante', emoji: '🤩' },
    ],
  },
  {
    id: 'style_vie',
    title: 'En alignement avec mon style de vie',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'calme_routine', label: 'Calme & routine stable', emoji: '🧘' },
      { value: 'social', label: 'Social & recevoir souvent', emoji: '🎉' },
      { value: 'mix', label: 'Mix (calme + recevoir)', emoji: '⚖️' },
      { value: 'pro', label: 'Pro / travail à la maison', emoji: '💻' },
      { value: 'nomade', label: 'Nomade / flexible', emoji: '🌍' },
    ],
  },
  {
    id: 'moment_cle',
    title: 'Moment clé',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'matin', label: 'Matin', emoji: '🌅' },
      { value: 'midi', label: 'Midi', emoji: '☀️' },
      { value: 'fin_aprem', label: "Fin d'après-midi", emoji: '🌤️' },
      { value: 'soir', label: 'Soir', emoji: '🌇' },
      { value: 'nuit', label: 'Nuit', emoji: '🌙' },
    ],
  },
  {
    id: 'style_prefere',
    title: 'Style préféré',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'moderne', label: 'Moderne / contemporain', emoji: '🏙️' },
      { value: 'tropical', label: 'Tropical / balinais', emoji: '🌴' },
      { value: 'minimaliste', label: 'Minimaliste', emoji: '🪴' },
      { value: 'boheme', label: 'Bohème', emoji: '🌺' },
      { value: 'industriel', label: 'Industriel / brut', emoji: '🏗️' },
      { value: 'intemporel', label: 'Intemporel', emoji: '⏳' },
    ],
  },
  {
    id: 'exterieurs',
    title: 'Extérieurs indispensables',
    type: 'multi',
    hasOther: true,
    options: [
      { value: 'jardin', label: 'Jardin', emoji: '🌳' },
      { value: 'terrasse', label: 'Terrasse', emoji: '🪑' },
      { value: 'piscine', label: 'Piscine', emoji: '🏊' },
      { value: 'vue', label: 'Vue', emoji: '🏔️' },
      { value: 'dedans_dehors', label: 'Dedans/dehors fluide', emoji: '🪟' },
      { value: 'pas_indispensable', label: 'Pas indispensable', emoji: '🤷' },
    ],
  },
  {
    id: 'sociabilite',
    title: 'Niveau de sociabilité du lieu',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'cocon', label: 'Cocon intime', emoji: '🤗' },
      { value: 'accueillant', label: 'Accueillant pour recevoir', emoji: '🍷' },
      { value: 'les_deux', label: 'Les deux (espaces séparés)', emoji: '⚖️' },
      { value: 'peu_importe', label: 'Peu importe', emoji: '🤷' },
    ],
  },
  {
    id: 'usage_principal',
    title: 'Usage principal',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'residence_principale', label: 'Résidence principale', emoji: '🏠' },
      { value: 'residence_secondaire', label: 'Résidence secondaire', emoji: '🏖️' },
      { value: 'investissement', label: 'Investissement pur (rentabilité)', emoji: '📈' },
      { value: 'mix', label: 'Mix (vivre + louer)', emoji: '🔄' },
      { value: 'projet_pro', label: 'Projet pro (location événementielle…)', emoji: '🎪' },
    ],
  },
  {
    id: 'calme',
    title: 'Calme & environnement',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'priorite', label: 'Priorité au calme', emoji: '🤫' },
      { value: 'souhaite', label: 'Calme souhaité mais pas obligatoire', emoji: '🙂' },
      { value: 'peu_importe', label: 'Peu importe si le bien compense', emoji: '🤷' },
    ],
  },
  {
    id: 'caractere',
    title: '"Caractère" vs "facile"',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'facile', label: 'Très facile à vivre (clé en main)', emoji: '🔑' },
      { value: 'un_peu', label: 'Un peu de caractère, ok', emoji: '🎭' },
      { value: 'atypique', label: "Atypique, j'adore", emoji: '🤩' },
      { value: 'a_discuter', label: 'À discuter', emoji: '💬' },
    ],
  },
  {
    id: 'declencheur',
    title: 'Déclencheur de coup de cœur',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'vue', label: 'Vue', emoji: '🏔️' },
      { value: 'lumiere', label: 'Lumière', emoji: '☀️' },
      { value: 'architecture', label: 'Architecture', emoji: '🏛️' },
      { value: 'materiaux', label: 'Matériaux / finitions', emoji: '🪵' },
      { value: 'piscine_exterieur', label: 'Piscine / extérieur', emoji: '🏊' },
      { value: 'agencement', label: 'Agencement', emoji: '🧩' },
      { value: 'chez_moi', label: 'Sensation "chez moi" immédiate', emoji: '🏡' },
    ],
  },
  {
    id: 'deal_breakers',
    title: 'Deal-breakers (refus absolus)',
    type: 'multi',
    hasOther: true,
    options: [
      { value: 'acces_complique', label: 'Accès compliqué', emoji: '🛤️' },
      { value: 'vis_a_vis', label: 'Vis-à-vis', emoji: '👁️' },
      { value: 'travaux', label: 'Travaux', emoji: '🔧' },
      { value: 'sombre', label: 'Sombre', emoji: '🌑' },
      { value: 'bruyant', label: 'Bruyant', emoji: '🔊' },
      { value: 'pas_exterieur', label: "Pas d'extérieur", emoji: '🚫' },
      { value: 'aucun', label: 'Aucun (je suis flexible)', emoji: '✅' },
    ],
  },
  {
    id: 'scene_ideale',
    title: 'Votre "scène idéale"',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'cafe_matin', label: 'Café calme le matin', emoji: '☕' },
      { value: 'aperos', label: 'Apéros / dîners entre amis', emoji: '🍷' },
      { value: 'piscine_soleil', label: 'Journées piscine & soleil', emoji: '☀️' },
      { value: 'famille', label: 'Moments famille', emoji: '👨‍👩‍👧' },
      { value: 'travailler', label: 'Travailler dans un bel espace', emoji: '💻' },
    ],
  },
  {
    id: 'trajectoire',
    title: 'Votre trajectoire',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'aujourdhui', label: "J'achète pour aujourd'hui", emoji: '📅' },
      { value: 'evoluer', label: "J'achète pour évoluer (famille / projets)", emoji: '📈' },
      { value: 'investir', label: "J'achète pour investir & optimiser", emoji: '💰' },
      { value: 'revente', label: 'Option de revente facile', emoji: '🔄' },
    ],
  },
  {
    id: 'animaux',
    title: 'Animaux',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'oui', label: "J'ai des animaux / j'en veux", emoji: '🐾' },
      { value: 'ok', label: "Je n'en ai pas mais ok", emoji: '👍' },
      { value: 'sans', label: 'Je préfère sans animaux', emoji: '🚫' },
    ],
  },
  {
    id: 'phrase_profil',
    title: 'Phrase "profil"',
    subtitle: 'Générateur',
    type: 'single',
    hasOther: true,
    options: [
      { value: 'apaise', label: '"Je cherche un lieu qui m\'apaise."', emoji: '🧘' },
      { value: 'inspire', label: '"Je cherche un lieu qui m\'inspire."', emoji: '💡' },
      { value: 'recevoir', label: '"Je cherche un lieu pour recevoir."', emoji: '🍷' },
      { value: 'simple', label: '"Je cherche un lieu simple, efficace."', emoji: '🏡' },
      { value: 'rare', label: '"Je cherche un lieu rare, avec du caractère."', emoji: '💎' },
      { value: 'rentable', label: '"Je cherche un lieu rentable et bien pensé."', emoji: '📈' },
    ],
  },
];
