project_id = "glefjdbehtumybpabkzj"

[functions.create-test-users]
verify_jwt = false

[functions.process-reminders]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.send-email]
verify_jwt = false
