
-- Create notification_templates table
CREATE TABLE public.notification_templates (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  step TEXT NOT NULL,
  channel TEXT NOT NULL CHECK (channel IN ('email', 'whatsapp')),
  recipient TEXT NOT NULL CHECK (recipient IN ('buyer', 'seller')),
  subject TEXT,
  body TEXT NOT NULL,
  variables JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN DEFAULT true,
  updated_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(step, channel, recipient)
);

-- Enable RLS
ALTER TABLE public.notification_templates ENABLE ROW LEVEL SECURITY;

-- Admin-only read
CREATE POLICY "Admins can view notification templates"
  ON public.notification_templates
  FOR SELECT
  USING (public.has_role(auth.uid(), 'admin'));

-- Admin-only insert
CREATE POLICY "Admins can insert notification templates"
  ON public.notification_templates
  FOR INSERT
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- Admin-only update
CREATE POLICY "Admins can update notification templates"
  ON public.notification_templates
  FOR UPDATE
  USING (public.has_role(auth.uid(), 'admin'));

-- Admin-only delete
CREATE POLICY "Admins can delete notification templates"
  ON public.notification_templates
  FOR DELETE
  USING (public.has_role(auth.uid(), 'admin'));

-- Service role read (for edge functions)
CREATE POLICY "Service role can read templates"
  ON public.notification_templates
  FOR SELECT
  USING (auth.role() = 'service_role');

-- Updated_at trigger
CREATE TRIGGER update_notification_templates_updated_at
  BEFORE UPDATE ON public.notification_templates
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Seed default email templates for all steps (buyer + seller)
-- Variables metadata per step
INSERT INTO public.notification_templates (step, channel, recipient, subject, body, variables) VALUES
-- MATCHED
('matched', 'email', 'buyer', '🎉 Nouveau match — Un bien correspond à vos critères !', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">🎉 Nouveau Match !</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">Un bien correspond à vos critères de recherche !</p><div style="background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid #667eea;"><p style="margin: 4px 0; color: #555;"><strong>Bien :</strong> {{property_type}}</p><p style="margin: 4px 0; color: #555;"><strong>Adresse :</strong> {{property_address}}</p><p style="margin: 4px 0; color: #555;"><strong>Prix :</strong> {{property_price}} {{property_currency}}</p></div><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Voir le détail</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "property_type", "property_address", "property_price", "property_currency", "action_url"]'::jsonb),

('matched', 'email', 'seller', '🎉 Nouveau match — Un acheteur s''intéresse à votre bien !', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">🎉 Nouveau Match !</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">Un acheteur s''intéresse à votre bien !</p><div style="background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid #667eea;"><p style="margin: 4px 0; color: #555;"><strong>Bien :</strong> {{property_type}}</p><p style="margin: 4px 0; color: #555;"><strong>Adresse :</strong> {{property_address}}</p><p style="margin: 4px 0; color: #555;"><strong>Prix :</strong> {{property_price}} {{property_currency}}</p></div><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Voir le détail</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "property_type", "property_address", "property_price", "property_currency", "action_url"]'::jsonb),

-- VISIT CONFIRMED
('visit_confirmed', 'email', 'buyer', '📅 Visite confirmée — Rendez-vous fixé !', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">📅 Visite Confirmée</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">Votre visite a été confirmée !</p><div style="background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid #11998e;"><p style="margin: 4px 0; color: #555;"><strong>📅 Date :</strong> {{visit_date_formatted}}</p><p style="margin: 4px 0; color: #555;"><strong>🏠 Bien :</strong> {{property_type}}</p><p style="margin: 4px 0; color: #555;"><strong>📍 Adresse :</strong> {{property_address}}</p></div><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Détails de la visite</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "property_type", "property_address", "visit_date_formatted", "action_url"]'::jsonb),

('visit_confirmed', 'email', 'seller', '📅 Visite confirmée — Rendez-vous fixé !', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">📅 Visite Confirmée</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">La visite de votre bien a été confirmée !</p><div style="background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid #11998e;"><p style="margin: 4px 0; color: #555;"><strong>📅 Date :</strong> {{visit_date_formatted}}</p><p style="margin: 4px 0; color: #555;"><strong>🏠 Bien :</strong> {{property_type}}</p><p style="margin: 4px 0; color: #555;"><strong>📍 Adresse :</strong> {{property_address}}</p></div><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Détails de la visite</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "property_type", "property_address", "visit_date_formatted", "action_url"]'::jsonb),

-- VISIT REMINDER
('visit_reminder', 'email', 'buyer', '⏰ Rappel : votre visite approche !', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">⏰ Rappel de Visite</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">Votre visite approche ({{reminder_type}}) !</p><div style="background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid #f5576c;"><p style="margin: 4px 0; color: #555;"><strong>📅</strong> {{visit_date_formatted}}</p><p style="margin: 4px 0; color: #555;"><strong>📍</strong> {{property_address}}</p></div><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Voir la transaction</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "property_address", "visit_date_formatted", "reminder_type", "action_url"]'::jsonb),

('visit_reminder', 'email', 'seller', '⏰ Rappel : visite de votre bien bientôt !', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">⏰ Rappel de Visite</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">Un acheteur visite votre bien bientôt ({{reminder_type}}) !</p><div style="background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid #f5576c;"><p style="margin: 4px 0; color: #555;"><strong>📅</strong> {{visit_date_formatted}}</p><p style="margin: 4px 0; color: #555;"><strong>📍</strong> {{property_address}}</p></div><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Voir la transaction</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "property_address", "visit_date_formatted", "reminder_type", "action_url"]'::jsonb),

-- OFFER MADE
('offer_made', 'email', 'seller', '💰 Nouvelle offre reçue !', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #f2994a 0%, #f2c94c 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">💰 Offre Reçue</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">Vous avez reçu une offre pour votre bien !</p><div style="background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid #f2994a;"><p style="margin: 4px 0; color: #555; font-size: 20px;"><strong>{{offer_amount}} {{property_currency}}</strong></p><p style="margin: 4px 0; color: #555;"><strong>Type :</strong> {{offer_type}}</p><p style="margin: 4px 0; color: #555;"><strong>Bien :</strong> {{property_type}} — {{property_address}}</p></div><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #f2994a 0%, #f2c94c 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Voir l''offre</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "property_type", "property_address", "property_currency", "offer_amount", "offer_type", "action_url"]'::jsonb),

('offer_made', 'email', 'buyer', '💰 Votre offre a été envoyée !', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #f2994a 0%, #f2c94c 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">💰 Offre Envoyée</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">Votre offre a bien été transmise au propriétaire.</p><div style="background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid #f2994a;"><p style="margin: 4px 0; color: #555; font-size: 20px;"><strong>{{offer_amount}} {{property_currency}}</strong></p><p style="margin: 4px 0; color: #555;"><strong>Bien :</strong> {{property_type}} — {{property_address}}</p></div><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #f2994a 0%, #f2c94c 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Suivre ma transaction</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "property_type", "property_address", "property_currency", "offer_amount", "offer_type", "action_url"]'::jsonb),

-- DEAL FINALIZED
('deal_finalized', 'email', 'buyer', '🎊 Deal finalisé — Félicitations !', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">🎊 Deal Finalisé !</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">Félicitations ! Votre transaction a été finalisée avec succès. 🏆</p><div style="background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid #667eea;"><p style="margin: 4px 0; color: #555;"><strong>Bien :</strong> {{property_type}}</p><p style="margin: 4px 0; color: #555;"><strong>Adresse :</strong> {{property_address}}</p></div><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Voir ma transaction</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "property_type", "property_address", "action_url"]'::jsonb),

('deal_finalized', 'email', 'seller', '🎊 Deal finalisé — Félicitations !', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">🎊 Deal Finalisé !</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">Félicitations ! Votre bien a été vendu avec succès. 🏆</p><div style="background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid #667eea;"><p style="margin: 4px 0; color: #555;"><strong>Bien :</strong> {{property_type}}</p><p style="margin: 4px 0; color: #555;"><strong>Adresse :</strong> {{property_address}}</p></div><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Voir ma transaction</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "property_type", "property_address", "action_url"]'::jsonb),

-- GENERIC
('generic', 'email', 'buyer', 'Notification SOMA', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">Notification</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">Vous avez une nouvelle notification sur SOMA.</p><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Voir les détails</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "action_url"]'::jsonb),

('generic', 'email', 'seller', 'Notification SOMA', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">Notification</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">Vous avez une nouvelle notification sur SOMA.</p><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Voir les détails</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "action_url"]'::jsonb),

-- INACTIVITY 12H
('inactivity_12h', 'email', 'buyer', '👋 Vous nous manquez sur SOMA !', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">👋 Revenez nous voir !</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">De nouveaux biens vous attendent sur SOMA. Ne manquez pas les dernières opportunités !</p><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Découvrir les biens</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "action_url"]'::jsonb),

('inactivity_12h', 'email', 'seller', '👋 Des acheteurs attendent sur SOMA !', '<div style="font-family: ''Segoe UI'', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;"><div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 32px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">👋 Revenez nous voir !</h1></div><div style="padding: 32px;"><p style="font-size: 16px; color: #333;">Bonjour <strong>{{recipient_name}}</strong>,</p><p style="font-size: 16px; color: #333;">Des acheteurs potentiels consultent vos biens. Restez actif pour maximiser vos chances !</p><div style="text-align: center; margin-top: 24px;"><a href="{{action_url}}" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; display: inline-block;">Voir mon tableau de bord</a></div></div><div style="padding: 16px 32px; background: #f1f3f5; text-align: center; font-size: 12px; color: #888;"><p>SOMA — La plateforme immobilière intelligente</p></div></div>', '["recipient_name", "action_url"]'::jsonb),

-- WHATSAPP TEMPLATES (text only, no subject)
('matched', 'whatsapp', 'buyer', NULL, '🎉 Bonjour {{recipient_name}} ! Un bien correspond à vos critères sur SOMA :\n\n🏠 {{property_type}} — {{property_address}}\n💰 {{property_price}} {{property_currency}}\n\n👉 {{action_url}}', '["recipient_name", "property_type", "property_address", "property_price", "property_currency", "action_url"]'::jsonb),

('matched', 'whatsapp', 'seller', NULL, '🎉 Bonjour {{recipient_name}} ! Un acheteur s''intéresse à votre bien sur SOMA :\n\n🏠 {{property_type}} — {{property_address}}\n\n👉 {{action_url}}', '["recipient_name", "property_type", "property_address", "action_url"]'::jsonb),

('visit_confirmed', 'whatsapp', 'buyer', NULL, '📅 Bonjour {{recipient_name}} ! Votre visite est confirmée :\n\n📅 {{visit_date_formatted}}\n🏠 {{property_type}} — {{property_address}}\n\n👉 {{action_url}}', '["recipient_name", "property_type", "property_address", "visit_date_formatted", "action_url"]'::jsonb),

('visit_confirmed', 'whatsapp', 'seller', NULL, '📅 Bonjour {{recipient_name}} ! Une visite de votre bien est confirmée :\n\n📅 {{visit_date_formatted}}\n🏠 {{property_type}} — {{property_address}}\n\n👉 {{action_url}}', '["recipient_name", "property_type", "property_address", "visit_date_formatted", "action_url"]'::jsonb),

('visit_reminder', 'whatsapp', 'buyer', NULL, '⏰ Rappel {{recipient_name}} ! Visite prévue ({{reminder_type}}) :\n\n📅 {{visit_date_formatted}}\n📍 {{property_address}}\n\n👉 {{action_url}}', '["recipient_name", "property_address", "visit_date_formatted", "reminder_type", "action_url"]'::jsonb),

('visit_reminder', 'whatsapp', 'seller', NULL, '⏰ Rappel {{recipient_name}} ! Visite de votre bien ({{reminder_type}}) :\n\n📅 {{visit_date_formatted}}\n📍 {{property_address}}\n\n👉 {{action_url}}', '["recipient_name", "property_address", "visit_date_formatted", "reminder_type", "action_url"]'::jsonb),

('offer_made', 'whatsapp', 'seller', NULL, '💰 Bonjour {{recipient_name}} ! Nouvelle offre reçue :\n\n💵 {{offer_amount}} {{property_currency}}\n🏠 {{property_type}} — {{property_address}}\n\n👉 {{action_url}}', '["recipient_name", "property_type", "property_address", "property_currency", "offer_amount", "action_url"]'::jsonb),

('offer_made', 'whatsapp', 'buyer', NULL, '💰 Bonjour {{recipient_name}} ! Votre offre a été envoyée :\n\n💵 {{offer_amount}} {{property_currency}}\n🏠 {{property_type}} — {{property_address}}\n\n👉 {{action_url}}', '["recipient_name", "property_type", "property_address", "property_currency", "offer_amount", "action_url"]'::jsonb),

('deal_finalized', 'whatsapp', 'buyer', NULL, '🎊 Félicitations {{recipient_name}} ! Votre transaction est finalisée !\n\n🏠 {{property_type}} — {{property_address}}\n\n👉 {{action_url}}', '["recipient_name", "property_type", "property_address", "action_url"]'::jsonb),

('deal_finalized', 'whatsapp', 'seller', NULL, '🎊 Félicitations {{recipient_name}} ! Votre bien a été vendu !\n\n🏠 {{property_type}} — {{property_address}}\n\n👉 {{action_url}}', '["recipient_name", "property_type", "property_address", "action_url"]'::jsonb),

('generic', 'whatsapp', 'buyer', NULL, 'Bonjour {{recipient_name}}, vous avez une nouvelle notification sur SOMA.\n\n👉 {{action_url}}', '["recipient_name", "action_url"]'::jsonb),

('generic', 'whatsapp', 'seller', NULL, 'Bonjour {{recipient_name}}, vous avez une nouvelle notification sur SOMA.\n\n👉 {{action_url}}', '["recipient_name", "action_url"]'::jsonb),

('inactivity_12h', 'whatsapp', 'buyer', NULL, '👋 Bonjour {{recipient_name}} ! De nouveaux biens vous attendent sur SOMA. Ne manquez pas les dernières opportunités !\n\n👉 {{action_url}}', '["recipient_name", "action_url"]'::jsonb),

('inactivity_12h', 'whatsapp', 'seller', NULL, '👋 Bonjour {{recipient_name}} ! Des acheteurs potentiels consultent vos biens sur SOMA.\n\n👉 {{action_url}}', '["recipient_name", "action_url"]'::jsonb);
