// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glefjdbehtumybpabkzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZWZqZGJlaHR1bXlicGFia3pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NDc0NTEsImV4cCI6MjA4NjAyMzQ1MX0.2GQ_ufVzpUJF941Ipq53UOfmdDRx_F4Nh_2wK4ucLxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});